# 🔮 TelegramSync - Конфигурация синхронизации
# ✨ Авторы: gordey25690 и DeepSeek

# Настройки Telegram бота
telegram:
  # Токен бота от @BotFather
  bot-token: "YOUR_BOT_TOKEN_HERE"
  # ID чата/канала (можно получить через @userinfobot)
  chat-id: "YOUR_CHAT_ID_HERE"
  # Включить бота
  enabled: true
  # Задержка между сообщениями (в миллисекундах)
  message-delay: 1000

# Настройки синхронизации
sync:
  # Синхронизировать глобальный чат Minecraft -> Telegram
  minecraft-to-telegram: true
  # Синхронизировать сообщения Telegram -> Minecraft
  telegram-to-minecraft: true
  # Включить форматирование сообщений
  enable-formatting: true
  # Максимальная длина сообщения
  max-message-length: 400

# Фильтрация сообщений
filter:
  # Игнорировать сообщения с этими словами
  blocked-words:
    - "реклама"
    - "спам"
    - "купить"
    - "продать"
  # Игнорировать сообщения от этих плагинов
  ignored-plugins:
    - "SomeSpamPlugin"
  # Разрешить сообщения от этих плагинов (пусто = все разрешены)
  allowed-plugins:
    - "XFilesPlugin"
    - "Essentials"
    - "EssentialsChat"

# Форматирование сообщений
format:
  # Формат сообщений из Minecraft в Telegram
  minecraft-to-telegram: "🎮 <player>: <message>"
  # Формат сообщений из Telegram в Minecraft
  telegram-to-minecraft: "📱 <username>: <message>"
  # Формат системных сообщений
  system-message: "⚡ <message>"
  # Формат сообщений от плагинов
  plugin-message: "🔮 <plugin>: <message>"

# Логирование
logging:
  # Включить логирование в файл
  enable-file-logging: true
  # Уровень детализации логов (INFO, DEBUG, ERROR)
  log-level: "INFO"
  # Сохранять историю сообщений
  save-message-history: true

# Вебхук настройки (для входящих сообщений)
webhook:
  # Использовать вебхук (требуется HTTPS домен)
  enabled: false
  # URL вебхука
  url: "https://yourdomain.com/telegram-webhook"
  # Секретный ключ
  secret: "your-secret-key"

# Автоматические сообщения
auto-messages:
  # Приветствие при входе игрока
  player-join: true
  # Прощание при выходе игрока  
  player-quit: true
  # Уведомления о достижениях # По умолчанию - false (Выкл)
  achievements: false
  # Уведомления о смерти
  deaths: true
